### ISSUE TITLE
Can not configure environment for qmpy to access mysql database

### ISSUE THREAD

**Issue by huzongxiang** [Tony-Y/cgnn#2]
pip and conda can not search pymatgen=2018.12.12
other versions installed through conda can not access MySQL  oqmd database, running your oqmd script has bugs.
How do I solve these problems?

conda create --name qmpy
conda install -n qmpy scikit-learn matplotlib python=2.7
source activate  qmpy
pip install pymatgen==2018.12.12 monty==1.0.3
pip install qmpy==1.2.0 ase==3.17
pip install pydash tqdm joblib

**Comment by Tony-Y** [comment]
I installed a Miniconda (https://repo.anaconda.com/miniconda/Miniconda3-py37_4.11.0-Linux-x86_64.sh) on a clean Linux machine (actually, I used Colab), and then the qmpy environment was successfully created. I didn't encounter any installation problem.

**Comment by huzongxiang** [comment]
> I installed a Miniconda (https://repo.anaconda.com/miniconda/Miniconda3-py37_4.11.0-Linux-x86_64.sh) on a clean Linux machine (actually, I used Colab), and then the qmpy environment was successfully created. I didn't encounter any installation problem.

Bugs occur when using pip install pymatgen，many sources of conda can not find pymatgen=2018.12.12. I want to use conda instead of pip but I have no idea which version of pymatgen I can use.

**Comment by Tony-Y** [comment]
Could you please look at [the installation log](https://gist.github.com/Tony-Y/32d30c4159707745ce3c9ee6debb3280). Pymatgen 2018.12.12 was successfully installed by pip on a clean Linux machine.

**Comment by huzongxiang** [comment]
> Could you please look at [the installation log](https://gist.github.com/Tony-Y/32d30c4159707745ce3c9ee6debb3280). Pymatgen 2018.12.12 was successfully installed by pip on a clean Linux machine.

hello，I install the pymatgen in a pure linux ubuntu. When starting a pip installation，the ubuntu environment has no gcc for libs like spglib. The mysqlclient should also be configured for qmpy installation.
Now, I have installed all libs successfully.

**Comment by huzongxiang** [comment]
> > Could you please look at [the installation log](https://gist.github.com/Tony-Y/32d30c4159707745ce3c9ee6debb3280). Pymatgen 2018.12.12 was successfully installed by pip on a clean Linux machine.
> 
> hello，I install the pymatgen in a pure linux ubuntu. When starting a pip installation，the ubuntu environment has no gcc for libs like spglib. The mysqlclient should also be configured for qmpy installation. Now, I have installed all libs successfully.

other problems occur when using qmpy ::sad

**Comment by huzongxiang** [comment]
> Could you please look at [the installation log](https://gist.github.com/Tony-Y/32d30c4159707745ce3c9ee6debb3280). Pymatgen 2018.12.12 was successfully installed by pip on a clean Linux machine.

I will try it in the colab.

**Comment by Tony-Y** [comment]
For Ubuntu 20.04 or later, MySQL 8.0 is default. But, the OQMD needs a MySQL 5.7 server. Please check your mysql version. If you use MySQL 8.0, see [an instruction](https://www.vultr.com/docs/how-to-install-mysql-5-7-on-ubuntu-20-04/) to install MySQL 5.7 on Ubuntu.

**Comment by huzongxiang** [comment]
> For Ubuntu 20.04 or later, MySQL 8.0 is default. But, the OQMD needs a MySQL 5.7 server. Please check your mysql version. If you use MySQL 8.0, see [an instruction](https://www.vultr.com/docs/how-to-install-mysql-5-7-on-ubuntu-20-04/) to install MySQL 5.7 on Ubuntu.

Thanks. Now, I can retrieve entries from mysql database successfully. I would like to know the specific format saved in .npz  of the transformation by using script oqmd_data.py. Is a entry in CIF, poscar or pymatgen.Structure format?

('Total Materials:', )
  0%|                                                   | 0/914 [00:00<?, ?it/s]
  1%|▍                                      | 10/914 [13:05<18:16:11, 72.76s/it]

**Comment by Tony-Y** [comment]
> I would like to know the specific format saved in .npz of the transformation by using script oqmd_data.py. Is a entry in CIF, poscar or pymatgen.Structure format?

The data format is almost the same as one of Materials Project REST API. So, the entry's structure is a pymatgen.Structure object.

**Comment by huzongxiang** [comment]
> pip install pymatgen==2018.12.12 monty==1.0.3

hello，I found that oqmd_data.py can consume large memory. 
Only 21% entries consume 6.9G/8G memory. Will the process terminate when reaching maximum of memory of the device?

**Comment by huzongxiang** [comment]
> > I would like to know the specific format saved in .npz of the transformation by using script oqmd_data.py. Is a entry in CIF, poscar or pymatgen.Structure format?
> 
> The data format is almost the same as one of Materials Project REST API. So, the entry's structure is a pymatgen.Structure object.

Thanks. I found that oqmd_data.py can consume large memory. 
Only 21% entries consume 6.9G/8G memory. Will the process terminate when reaching maximum of memory of the device?

**Comment by huzongxiang** [comment]
> > > I would like to know the specific format saved in .npz of the transformation by using script oqmd_data.py. Is a entry in CIF, poscar or pymatgen.Structure format?
> > 
> > 
> > The data format is almost the same as one of Materials Project REST API. So, the entry's structure is a pymatgen.Structure object.
> 
> Thanks. I found that oqmd_data.py can consume large memory. Only 21% entries consume 6.9G/8G memory. Will the process terminate when reaching maximum of memory of the device?

The process terminates when memory reaches maximum，why the loop of np.save_compressed consumes increased memory?

**Comment by Tony-Y** [comment]
The memory consumption is almost constant because the number of entries processed at each iteration does not excess `chunk_size`:

https://github.com/Tony-Y/cgnn/blob/c6c28e6eaf420665a01bd4e5b72b3ac20ff6b138/tools/oqmd_data.py#L105

Please change to `chunk_size=250` to reduce the memory consumption.

**Comment by Tony-Y** [comment]
Could you check `innodb_buffer_pool_size` of MySQL?
```
mysql -u root -p
mysql> show variables like 'innodb_buffer_pool_size';
```

This variable limits the memory consumption of MySQL.

**Comment by huzongxiang** [comment]
> The memory consumption is almost constant because the number of entries processed at each iteration does not excess `chunk_size`:
> 
> https://github.com/Tony-Y/cgnn/blob/c6c28e6eaf420665a01bd4e5b72b3ac20ff6b138/tools/oqmd_data.py#L105
> 
> Please change to `chunk_size=250` to reduce the memory consumption.

thanks

**Comment by Tony-Y** [comment]
https://github.com/Tony-Y/cgnn/blob/c6c28e6eaf420665a01bd4e5b72b3ac20ff6b138/tools/oqmd_data.py#L116

Change `03d` to `04d` if you set `chunk_size=250`  because there are 561,888 entries.

**Comment by xiezhen087** [comment]
I‘m sorry, but I have tried several structures. I found that only the example SiO2's crystal graph was right. I don't know why .

**Comment by Tony-Y** [comment]
I want to clarify what you did. Did you compare the official graph_data.npz in [OQMD v1.2 dataset](https://zenodo.org/record/7118055/files/oqmd-v1_2-for-cgnn.7z?download=1) with one that you generated according to [the instruction](https://github.com/Tony-Y/cgnn/tree/master/OQMD)?

**Comment by xiezhen087** [comment]
> I want to clarify what you did. Did you compare the official graph_data.npz in [OQMD v1.2 dataset](https://zenodo.org/record/7118055/files/oqmd-v1_2-for-cgnn.7z?download=1) with one that you generated according to [the instruction](https://github.com/Tony-Y/cgnn/tree/master/OQMD)?

well, the data I used are not the official OQMD v1.2 dataset, but they are from the Material Project which have been relaxed in VASP and been used to calculate the phonon spectrum.

**Comment by Tony-Y** [comment]
Your issue is very off-topic in this thread. Please create an issue by pushing the `New issue` green button above. In addition, give me enough information to reproduce your problems.

**Comment by xiezhen087** [comment]
> Your issue is very off-topic in this thread. Please create an issue by pushing the `New issue` green button above. In addition, give me enough information to reproduce your problems.

OK，thanks. I think I have found some clues of this problem.

**Comment by Tony-Y** [comment]
> Thanks. I found that oqmd_data.py can consume large memory. Only 21% entries consume 6.9G/8G memory. Will the process terminate when reaching maximum of memory of the device?

Using a qmpy environment, configured according to [the latest instruction](https://github.com/Tony-Y/cgnn/blob/0a56f88313696795e6ef8443e8618db39f0b8184/OQMD/README.md) as of Dec 9, 2022, on an Ubuntu 18.04 docker container, I couldn't observe high memory consumption﻿ when executing `oqmd_data.py`.

I will publish my docker image for the qmpy environment to Docker Hub soon.

**Comment by Tony-Y** [comment]
I have just published my Docker image. Details are in [CGNN v1.0.3 Release Notes](https://github.com/Tony-Y/cgnn/releases/tag/v1.0.3).
